#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
ulauncher --hide-window --no-window-shadow &

bspc monitor DP-2 -d I II 
bspc monitor HDMI-0 -d browser code slack zoom VII

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop=^3
bspc rule -a Slack desktop=^5
bspc rule -a Zoom desktop=^6
bspc rule -a ulauncher focus=on
bspc rule -a polybar border=off manage=off

/home/fred/.config/polybar/launch.sh &
dunst &

