#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
ulauncher --hide-window --no-window-shadow &

bspc monitor -d browser code slack IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^1'
bspc rule -a slack desktop='^3'
bspc rule -a ulauncher focus=on
bspc rule -a polybar border=off manage=off

/home/fred/.config/polybar/launch.sh &
dunst &

